### ISSUE TITLE
Feature request: periodical updates

### ISSUE THREAD

**Issue by exoego** [sosukesuzuki/nodejs-api-table#1]
It would be helpful if [the hosted table](https://nodejs-api-table.netlify.app/) is updated periodically (e.g. daily or weekly).

**Comment by sosukesuzuki** [comment]
Fixed by https://github.com/sosukesuzuki/nodejs-api-table/blob/main/.github/workflows/deploy.yml. Our website will be updated weekly or manually.

Also now last fetched date is included in header.

<img width="998" alt="スクリーンショット 2021-09-14 0 07 16" src="https://user-images.githubusercontent.com/14838850/133108936-de44850d-9994-4d56-a098-59ba72d95b08.png">
